"""empty message

Revision ID: 295ba81690ff
Revises: 605fc26ad3d7
Create Date: 2024-08-26 15:57:46.869801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '295ba81690ff'
down_revision = '605fc26ad3d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_list', schema=None) as batch_op:
        batch_op.alter_column('list_id',
               existing_type=mysql.INTEGER(),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment='用户id',
               existing_nullable=False)
        batch_op.alter_column('last_message_id',
               existing_type=mysql.INTEGER(),
               comment='会话id',
               existing_nullable=False)
        batch_op.drop_constraint('chat_list_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('chat_list_ibfk_1', type_='foreignkey')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('message_id',
               existing_type=mysql.INTEGER(),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('sender_id',
               existing_type=mysql.INTEGER(),
               comment='送信者id',
               existing_nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               comment='聊天信息',
               existing_nullable=False)
        batch_op.alter_column('timetamp',
               existing_type=mysql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('message_ibfk_1', type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=128),
               comment='密码',
               existing_comment='密码，加密保存',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=128),
               comment='密码，加密保存',
               existing_comment='密码',
               existing_nullable=True)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_foreign_key('message_ibfk_1', 'user', ['sender_id'], ['id'])
        batch_op.alter_column('timetamp',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='聊天信息',
               existing_nullable=False)
        batch_op.alter_column('sender_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='送信者id',
               existing_nullable=False)
        batch_op.alter_column('message_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('chat_list', schema=None) as batch_op:
        batch_op.create_foreign_key('chat_list_ibfk_1', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('chat_list_ibfk_2', 'message', ['last_message_id'], ['message_id'])
        batch_op.alter_column('last_message_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='会话id',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户id',
               existing_nullable=False)
        batch_op.alter_column('list_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
