"""empty message

Revision ID: 3faee8af91d3
Revises: 295ba81690ff
Create Date: 2024-08-27 12:34:57.078528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3faee8af91d3'
down_revision = '295ba81690ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bot_id', sa.Integer(), nullable=False, comment='botid'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('bot_id')

    # ### end Alembic commands ###
