"""empty message

Revision ID: af386407ddec
Revises: 3faee8af91d3
Create Date: 2024-08-27 13:09:39.254239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af386407ddec'
down_revision = '3faee8af91d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_id', sa.Integer(), nullable=False, comment='记录id'))
        batch_op.drop_column('bot_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bot_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='botid'))
        batch_op.drop_column('list_id')

    # ### end Alembic commands ###
